/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectcinema;

/**
 *
 * @author Sofi
 */
public class SelectMovie extends javax.swing.JFrame {

    /** Creates new form SelectMovie */
    public SelectMovie() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectMovie = new javax.swing.JLabel();
        cmbMovies = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblSchedule = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblRoom = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox<>();
        ckbVIP = new javax.swing.JCheckBox();
        ckb3D = new javax.swing.JCheckBox();
        ckb2D = new javax.swing.JCheckBox();
        rbtnSub = new javax.swing.JRadioButton();
        rbtnDob = new javax.swing.JRadioButton();
        btnExitSelectMovie = new javax.swing.JButton();
        btnContinueSelectMovie = new javax.swing.JButton();
        lblWallpaperMovies = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelectMovie.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblSelectMovie.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectMovie.setText("Seleccione la pelicula");
        getContentPane().add(lblSelectMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        cmbMovies.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        cmbMovies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 240, -1));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 420, 540));

        lblSchedule.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lblSchedule.setText("Seleccione el Horario");
        getContentPane().add(lblSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 240, -1));

        lblRoom.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblRoom.setForeground(new java.awt.Color(255, 255, 255));
        lblRoom.setText("Seleccione la Sala");
        getContentPane().add(lblRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        lblLocation.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Localidad");
        getContentPane().add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        cmbLocation.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 240, -1));

        ckbVIP.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        ckbVIP.setForeground(new java.awt.Color(255, 255, 255));
        ckbVIP.setText("VIP");
        getContentPane().add(ckbVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        ckb3D.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        ckb3D.setForeground(new java.awt.Color(255, 255, 255));
        ckb3D.setText("3D");
        getContentPane().add(ckb3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, -1, -1));

        ckb2D.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        ckb2D.setForeground(new java.awt.Color(255, 255, 255));
        ckb2D.setText("2D");
        getContentPane().add(ckb2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, -1, -1));

        rbtnSub.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        rbtnSub.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSub.setText("Subtitulada");
        getContentPane().add(rbtnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, -1, -1));

        rbtnDob.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        rbtnDob.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDob.setText("Doblada");
        getContentPane().add(rbtnDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, -1, -1));

        btnExitSelectMovie.setFont(new java.awt.Font("Hobo Std", 1, 12)); // NOI18N
        btnExitSelectMovie.setText("SALIR");
        btnExitSelectMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSelectMovieActionPerformed(evt);
            }
        });
        getContentPane().add(btnExitSelectMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 730, -1, -1));

        btnContinueSelectMovie.setFont(new java.awt.Font("Hobo Std", 1, 12)); // NOI18N
        btnContinueSelectMovie.setText("CONTINUAR");
        getContentPane().add(btnContinueSelectMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 730, -1, -1));

        lblWallpaperMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginPics/WallpaperCinema2.jpg"))); // NOI18N
        lblWallpaperMovies.setText("jLabel1");
        getContentPane().add(lblWallpaperMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1921, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnExitSelectMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSelectMovieActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitSelectMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinueSelectMovie;
    private javax.swing.JButton btnExitSelectMovie;
    private javax.swing.JCheckBox ckb2D;
    private javax.swing.JCheckBox ckb3D;
    private javax.swing.JCheckBox ckbVIP;
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JComboBox<String> cmbMovies;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblSelectMovie;
    private javax.swing.JLabel lblWallpaperMovies;
    private javax.swing.JRadioButton rbtnDob;
    private javax.swing.JRadioButton rbtnSub;
    // End of variables declaration//GEN-END:variables

}
